export enum gameTypes {
  FETCH_GAME_REQUEST = 'FETCH_GAME_REQUEST',
  FETCH_GAME_SUCCESS = 'FETCH_GAME_SUCCESS',
  FETCH_GAME_FAILURE = 'FETCH_GAME_FAILURE',
  ADD_GAME_REQUEST = 'ADD_GAME_REQUEST',
  ADD_GAME_REQUEST_SUCCESS = 'ADD_GAME_REQUEST_SUCCESS',
  ADD_GAME_REQUEST_FAILURE = 'ADD_GAME_REQUEST_FAILURE',
}
