version: '2'

services:
  backend-api:
    image: game-catalog
    container_name: backend-api
    ports:
      - "8080:8080"
    depends_on:
      - db-postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-postgres:5432/postgresdb
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db-postgres:
    build: ./src/database
    ports:
      - "5433:5432"
    container_name: db-postgres
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres

  game-catalog-front-end:
    build: ../game-catalog-front-end/
    ports:
      - "3000:3000"
    depends_on:
      - backend-api